<a href="https://colab.research.google.com/github/anaberereta-hue/Trabajos-Algebraa/blob/main/Factorizacion_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *FACTORIZACIÓN LU*

Integrantes:

Francisco Narváez

Dilan

Anahí Real

#**1.Introducción a la Factorización LU**

###**¿Qúe es la factorizacion LU?**

La factorizacion LU es una herramienta de resolución de matrices  implica que la matriz cuadrada $A$ se divide en dos matrices más sencillas donde la una matriz inferior L de (lower) y la matriz superior U (upper) se vuelven sistema de resolución más optimizado.

Esta herramienta es importante en Algebra Lineal ya que ayuda a resolver sistemas de ecuaciones de forma más sencilla, encontrando asi de forma más fácil el determinante, inversa o el rango de matriz.


Los componentes de factorizacion LU son:

* Matriz Lower → Una matriz triangular inferior es donde los ceros estan encima de su diagonal principal.

$$A ⇒  \begin{bmatrix}
a_{11} & 0 & 0 \\
a_{21} & a_{22} & 0 \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}$$

* Matriz Upper → Una matriz superior es donde los terminos que forman una triangulo de ceros es bajo la diagonal principal.
$$A ⇒  \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
0 & a_{22} & a_{23} \\
0 & 0 & a_{33}
\end{bmatrix}$$


La ventaja de resolverlo sin usar unicamente la reducción de Gauss aparece cuando tenemos que resolver el sistema $Ax = b$ para muchos vectores $b$ diferentes pero con la misma matriz $A$. En lugar de repetir Gauss cada vez, se factoriza una sola vez y luego se  resuelven dos sistemas muy sencillos mediante sustitución:
* Se resuelve $Ly = b$ (Sustitución hacia adelante).
* Se Resuelve $Ux = y$ (Sustitución hacia atrás).

###**Procedimiento**

* **Paso 1:** Es conveniente que preparemos las matrices y poder avanzar de forma ordenada hacia donde queremos llegar. Es decir, supongamos que tenemos una matriz $A$ de $3x3$ y lo que queremos hacer es de $A$ llegar a las matices $L$ y $U$. Es decir, la organización deberá tener la forma $A$=$LU$

$$A \Rightarrow\ \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix} = L \rightarrow\ \begin{bmatrix} 1 & 0 & 0 \\ l_{21} & 1 & 0 \\ l_{31} & l_{32} & 1 \end{bmatrix} \cdot U \rightarrow\ \begin{bmatrix} u_{11} & u_{12} & u_{13} \\ 0 & u_{22} & u_{23} \\ 0 & 0 & u_{33} \end{bmatrix} $$

*Es decir, esta será la forma final de la matriz donde los valores $l_{ij}$ y de $u_{ij}$ serán los resultados del proceso.*

* **Paso 2: Obtención de la Matriz U (Upper Triangular o Trangular Superior)**

El objetivo principal es transformar la matriz $A$ en una matriz triangular superior $U$ utilizando operaciones elementales de fila ( o sea la eliminación Gaussiana). Estas operaciones se aplican para hacer ceros por debajo de la diagonal principal.

Tenemos nuestra matriz $A$ de $3x3$:

$$A = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}$$

- Paso 2.1: Para obtener nuestra matriz $U$ debemos hacer ceros en la primera columna debajo de $a_{11}$

Para hacer $a_{21}$ cero, aplicamos la operación de fila $F_2 \leftarrow F_2 - (\frac{a_{21}}{a_{11}})F_1$.
El multiplicador es $l_{21} = \frac{a_{21}}{a_{11}}$. Anotamos el resultado de dicha división en la posición $l_{21}$ de la matriz $L$

Para hacer $a_{31}$ cero, aplicamos la operación de fila $F_3 \leftarrow F_3 - (\frac{a_{31}}{a_{11}})F_1$.
El multiplicador es $l_{31} = \frac{a_{31}}{a_{11}}$. También anotamos el resultado de dicha división en la posición $l_{31}$ de la matriz $L$

Después de estas operaciones, la matriz se verá así:

$$\begin{bmatrix} a_{11} & a_{12} & a_{13} \\ 0 & a'_{22} & a'_{23} \\ 0 & a'_{32} & a'_{33} \end{bmatrix} $$

Mientras que la Matriz $L$ tendrá anotados ya los elementos de la primera columna bajo $a_{11}$, es decir $l_{21}$ $l_{31}$

* Paso 2.2: Hacer ceros en la segunda columna debajo de $a'_{22}$

Ahora, para hacer $a'_{32}$ cero, aplicamos la operación de fila $F_3 \leftarrow F_3 - (\frac{a'_{32}}{a'_{22}})F_2$.
El multiplicador es $l_{32} = \frac{a'_{32}}{a'_{22}}$. Y anotamos por último el resultado de la división (el multiplicador) en la posición $l_{32}$ de la matriz $L$.

Finalmente, obtenemos la matriz $U$:

$$U = \begin{bmatrix} u_{11} & u_{12} & u_{13} \\ 0 & u_{22} & u_{23} \\ 0 & 0 & u_{33} \end{bmatrix}$$

Donde $u_{ij}$ son los elementos de la matriz resultante después de la eliminación Gaussiana.


* **Paso 3: Obtención y revisión de la Matriz L (Lower Triangular)**

La matriz $L$ (lower triangular) se construye con los multiplicadores que utilizamos en el proceso de eliminación Gaussiana para obtener $U$.

$$L = \begin{bmatrix} 1 & 0 & 0 \\ l_{21} & 1 & 0 \\ l_{31} & l_{32} & 1 \end{bmatrix}$$

Donde:
* $l_{21} = \frac{a_{21}}{a_{11}}$ (el multiplicador para hacer cero $a_{21}$)
* $l_{31} = \frac{a_{31}}{a_{11}}$ (el multiplicador para hacer cero $a_{31}$)
* $l_{32} = \frac{a'_{32}}{a'_{22}}$ (el multiplicador para hacer cero $a'_{32}$)

**Etiqueta:** *Multiplicadores de Eliminación Gaussiana*

Con $L$ y $U$ obtenidas, hemos concluido la factorización de la matriz $A$ en el producto de una matriz triangular inferior $L$ y una matriz triangular superior $U$, es decir, $A = LU$.

#**2. Guión y videotutorial de factorización LU**

#**3. Herramienta computacional para factorización LU**






# **4. Aplicación práctica de la Factorizacion LU**
###* **Aplicacion en Ingeniería Estructural (Equilibrio de Fuerzas)**

Gemini ha dicho
En ingeniería estructural, la factorización LU es fundamental cuando se analizan estructuras estáticamente determinadas o indeterminadas (como cerchas, marcos o vigas) mediante el Método de la Rigidez.


1. El Problema: Una Cercha de dos barras
Imagina un nodo superior donde se unen dos barras de acero que están ancladas al suelo. Aplicamos una carga externa $P$ (una fuerza con componentes en $x$ e $y$) y queremos encontrar los desplazamientos del nodo ($d_1, d_2$).

El equilibrio de la estructura se define por la ecuación fundamental:

$$K \cdot \mathbf{d} = \mathbf{F}$$
Donde:

$K$: Matriz de rigidez global (propiedades del material y geometría).

$d$: Vector de desplazamientos desconocidos.

$F$: Vector de cargas externas aplicadas.

###* **Aplicacion en Economía (Modelo de insumo-producto o similar)**

La factorización $LU$ es una herramienta fundamental en el álgebra lineal computacional, y su aplicación en economía es especialmente potente cuando trabajamos con el **Modelo de Insumo-Producto de Leontief**.

Este modelo busca determinar los niveles de producción necesarios para satisfacer tanto la demanda intermedia (entre industrias) como la demanda externa (consumidores).


## 1. El Modelo de Leontief y el Sistema Lineal
El modelo se expresa mediante la ecuación:
$$x = Cx + d$$

Donde:
* $x$: Vector de producción total.
* $C$: Matriz de coeficientes tecnológicos (qué tanto de un insumo requiere cada industria).
* $d$: Vector de demanda final.

Para resolverlo, despejamos $x$:
$$(I - C)x = d$$
Definimos $A = (I - C)$, lo que nos deja con un sistema de ecuaciones lineales $Ax = d$.

Formulación de problema real

# 1. CONTEXTO DEL PROBLEMA (COMENTARIOS E IMPRESIÓN)
# Problema: Análisis de Interdependencia Económica (Minería y Energía)

## 1. Contexto del Problema
El Ministerio de Economía busca determinar los niveles de producción necesarios
para satisfacer una demanda externa, considerando que cada sector consume insumos de sí mismo y del otro para operar.

### Datos de Consumo (Coeficientes Tecnológicos):
* Para producir $1 de Minería (Sector 1):
- Se requieren $0.20 de Minería (Autoconsumo).
        - Se requieren $0.50 de Energía (Insumo externo).
    * Para producir $1 de Energía (Sector 2):
        - Se requieren $0.40 de Minería (Insumo externo).
        - Se requieren $0.10 de Energía (Autoconsumo).

    ### Demandas Finales (Exportación):
    * Minerales (d1): $100 millones.
    * Energía (d2): $50 millones.
    """
    print(contexto)

    # =========================================================================
    # 2. PLANTEAMIENTO MATEMÁTICO
    # =========================================================================
    
    # Matriz de coeficientes tecnológicos (C)
    C = np.array([
        [0.2, 0.4],
        [0.5, 0.1]
    ])

    # Vector de demanda externa (d)
    d = np.array([100.0, 50.0])

    # Matriz de Leontief: A = (I - C)
    A = np.eye(2) - C

    print("-" * 60)
    print("MATRIZ DE LEONTIEF (A = I - C):")
    print(A)
    print(f"\nVECTOR DE DEMANDA EXTERNA (d): {d}")
    print("-" * 60)

    # =========================================================================
    # 3. RESOLUCIÓN MEDIANTE FACTORIZACIÓN LU (PASO A PASO)
    # =========================================================================
    
    # PASO 1: Factorización A = LU
    # Calculamos el multiplicador m21 para hacer cero el elemento A[1,0]
    m21 = A[1, 0] / A[0, 0]
    
    L = np.array([
        [1.0, 0.0],
        [m21, 1.0]
    ])
    
    U = np.array([
        [A[0, 0], A[0, 1]],
        [0.0, A[1, 1] - (m21 * A[0, 1])]
    ])

    print("\n[PASO 1] FACTORIZACIÓN LU:")
    print(f"L = \n{L}")
    print(f"U = \n{U}")

    # PASO 2: Sustitución hacia adelante (Ly = d)
    # y1 = d1
    # y2 = d2 - m21*y1
    y = np.zeros(2)
    y[0] = d[0]
    y[1] = d[1] - (L[1, 0] * y[0])

    print(f"\n[PASO 2] SUSTITUCIÓN HACIA ADELANTE (Ly = d):")
    print(f"Vector intermedio y = {y}")

    # PASO 3: Sustitución hacia atrás (Ux = y)
    # x2 = y2 / U[1,1]
    # x1 = (y1 - U[0,1]*x2) / U[0,0]
    x = np.zeros(2)
    x[1] = y[1] / U[1, 1]
    x[0] = (y[0] - U[0, 1] * x[1]) / U[0, 0]

    print(f"\n[PASO 3] SUSTITUCIÓN HACIA ATRÁS (Ux = y):")
    print(f"RESULTADO FINAL (Producción Necesaria):")
    print(f"Producción Total Minería (x1): ${x[0]:.2f} millones")
    print(f"Producción Total Energía (x2): ${x[1]:.2f} millones")
    
    print("-" * 60)
    print("CONCLUSIÓN:")
    print(f"Para entregar ${np.sum(d)}M al exterior, la economía debe producir")
    print(f"un total bruto de ${np.sum(x):.2f}M debido a la interdependencia.")

# Ejecutar la función
if __name__ == "__main__":
    resolver_modelo_leontief()
###* **Aplicacion en Ciencias Ambientales (Movimiento o dispersión de contaminantes)**

En Ciencias Ambientales la factorización LU permite respuestas inmediatas, ya que funciona como una herramienta que simula modelos lo que seria los sistemas de ecuaciones por lo que al aplicar este metodo si existe un cambio en terminos independientes solo se harían sustituciones en vez de desarrollarse desde 0 toda la resolucion.

* Aplicación: Un cientifico de Datos trabaja en una organización de
ambiental y monitorea la salud del ecosistema hibrido en las Islas Galápagos, allí el sistema cuenta con 3 lagos interconectados. Y en estos se detecta un fertilizante no identificado y se necesita calcular la concentracion de cada lago para activar una alerta del contaminante invasor.
Ahora el flujo de estos lagos crean un equilibrio dinamico por lo que se puede modelar a un sistema de ecuaciones, las incognitas x1,x2,x3 representan las concentraciones.

Lago A (Entrada principal) $2x_1-x_2-x_3=9$

Lago B (Interconexión) $4x_1 + 3x_2 + 3x_3 = 23$

Lago C (Salida al mar) $2x_1 + x_2 + 2x_3 = 10$

1. Representación Matricial ($Ax = b$)

La matriz de coeficientes $A$ representa la estructura física de conexión entre los lagos:$$A = \begin{pmatrix} 2 & 1 & 1 \\ 4 & 3 & 3 \\ 2 & 1 & 2 \end{pmatrix}, \quad b = \begin{pmatrix} 9 \\ 23 \\ 10 \end{pmatrix}$$

2. Factorización LU (Comandos de Python)

Matriz L (Lower): Contiene los multiplicadores del flujo.$$L = \begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ 1 & 0 & 1 \end{pmatrix}$$Matriz U (Upper): Contiene el sistema simplificado tras la eliminación.
$$U = \begin{pmatrix} 2 & 1 & 1 \\ 0 & 1 & 1 \\ 0 & 0 & 1 \end{pmatrix}$$

3. Sustitución y Resultados

Primero resolvemos $Ly = b$ para encontrar un estado intermedio del sistema, y luego $Ux = y$ para hallar las concentraciones finales.
Resultado de la ejecución:

$x_1$ (Lago A): $2.0$ mg/L

$x_2$ (Lago B): $4.0$ mg/L

$x_3$ (Lago C): $1.0$ mg/L

##Resolución de Sistemas de Ecuaciones


# Ejercicio de aplicación en Ingeniería

# Ejercicio de aplicación en Economía

# Ejercicio de aplicación en Ciencias Ambientales

In [ ]:
import numpy as np

def factorizacion_lu_paso_a_paso(A_in, b_in):
    A = A_in.copy().astype(float)
    b = b_in.copy().astype(float)
    n = len(A)
    L = np.eye(n) # Matriz Identidad inicial

    print("=== PROCESO DE FACTORIZACIÓN LU ===\n")
    print("Matriz inicial A:")
    print(A)
    print("-" * 30)

    # Eliminación Gaussiana para encontrar L y U
    for i in range(n):
        for j in range(i + 1, n):
            # Calcular el factor (multiplicador)
            factor = A[j, i] / A[i, i]
            L[j, i] = factor

            print(f"Operación: Fila {j+1} = Fila {j+1} - ({factor:.2f}) * Fila {i+1}")

            # Aplicar la operación a la fila de la matriz A
            A[j, i:] = A[j, i:] - factor * A[i, i:]

            print(A)
            print("-" * 30)

    U = A
    print("\n[RESULTADO DE LA DESCOMPOSICIÓN]")
    print(f"Matriz L (Multiplicadores):\n{L}")
    print(f"\nMatriz U (Triangular Superior):\n{U}")
    print("=" * 35)

    # Resolución del sistema: Ly = b (Sustitución hacia adelante)
    y = np.zeros(n)
    for i in range(n):
        sum_ly = np.dot(L[i, :i], y[:i])
        y[i] = b[i] - sum_ly

    print(f"\n1. Resolviendo Ly = b para y:")
    print(f"Vector intermedio y: {y}")

    # Resolución del sistema: Ux = y (Sustitución hacia atrás)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        sum_ux = np.dot(U[i, i+1:], x[i+1:])
        x[i] = (y[i] - sum_ux) / U[i, i]

    print(f"\n2. Resolviendo Ux = y para x:")
    print(f"Vector solución final x: {x}")
    print("\n" + "=" * 35)

# --- Datos del problema ---
A_lacos = np.array([
    [2, 1, 1],
    [4, 3, 3],
    [2, 1, 2]
])
b_lagos = np.array([9, 23, 10])

# Ejecutar la función
factorizacion_lu_paso_a_paso(A_lacos, b_lagos)

=== PROCESO DE FACTORIZACIÓN LU ===

Matriz inicial A:
[[2. 1. 1.]
 [4. 3. 3.]
 [2. 1. 2.]]
------------------------------
Operación: Fila 2 = Fila 2 - (2.00) * Fila 1
[[2. 1. 1.]
 [0. 1. 1.]
 [2. 1. 2.]]
------------------------------
Operación: Fila 3 = Fila 3 - (1.00) * Fila 1
[[2. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
------------------------------
Operación: Fila 3 = Fila 3 - (0.00) * Fila 2
[[2. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
------------------------------

[RESULTADO DE LA DESCOMPOSICIÓN]
Matriz L (Multiplicadores):
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]

Matriz U (Triangular Superior):
[[2. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]

1. Resolviendo Ly = b para y:
Vector intermedio y: [9. 5. 1.]

2. Resolviendo Ux = y para x:
Vector solución final x: [2. 4. 1.]



# Conclusión


# Referencias

Larson, R. (2015). Fundamentos de álgebra lineal (7.ª ed.). Cengage Learning.

