<a href="https://colab.research.google.com/github/anaberereta-hue/Trabajos-Algebraa/blob/main/Factorizacion_LU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *FACTORIZACIÓN LU*

Integrantes:

Francisco Narváez

Dilan Flores

Anahí Real

#**1.Introducción a la Factorización LU**

###**¿Qúe es la factorizacion LU?**

La factorizacion LU es una herramienta de resolución de matrices  implica que la matriz cuadrada $A$ se divide en dos matrices más sencillas donde la una matriz inferior L de (lower) y la matriz superior U (upper) se vuelven sistema de resolución más optimizado.

Esta herramienta es importante en Algebra Lineal ya que ayuda a resolver sistemas de ecuaciones de forma más sencilla, encontrando asi de forma más fácil el determinante, inversa o el rango de matriz.


Los componentes de factorizacion LU son:

* Matriz Lower → Una matriz triangular inferior es donde los ceros estan encima de su diagonal principal.

$$A ⇒  \begin{bmatrix}
a_{11} & 0 & 0 \\
a_{21} & a_{22} & 0 \\
a_{31} & a_{32} & a_{33}
\end{bmatrix}$$

* Matriz Upper → Una matriz superior es donde los terminos que forman una triangulo de ceros es bajo la diagonal principal.
$$A ⇒  \begin{bmatrix}
a_{11} & a_{12} & a_{13} \\
0 & a_{22} & a_{23} \\
0 & 0 & a_{33}
\end{bmatrix}$$


La ventaja de resolverlo sin usar unicamente la reducción de Gauss aparece cuando tenemos que resolver el sistema $Ax = b$ para muchos vectores $b$ diferentes pero con la misma matriz $A$. En lugar de repetir Gauss cada vez, se factoriza una sola vez y luego se  resuelven dos sistemas muy sencillos mediante sustitución:
* Se resuelve $Ly = b$ (Sustitución hacia adelante).
* Se Resuelve $Ux = y$ (Sustitución hacia atrás).

###**Procedimiento**

* **Paso 1:** Es conveniente que preparemos las matrices y poder avanzar de forma ordenada hacia donde queremos llegar. Es decir, supongamos que tenemos una matriz $A$ de $3x3$ y lo que queremos hacer es de $A$ llegar a las matices $L$ y $U$. Es decir, la organización deberá tener la forma $A$=$LU$

$$A \Rightarrow\ \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix} = L \rightarrow\ \begin{bmatrix} 1 & 0 & 0 \\ l_{21} & 1 & 0 \\ l_{31} & l_{32} & 1 \end{bmatrix} \cdot U \rightarrow\ \begin{bmatrix} u_{11} & u_{12} & u_{13} \\ 0 & u_{22} & u_{23} \\ 0 & 0 & u_{33} \end{bmatrix} $$

*Es decir, esta será la forma final de la matriz donde los valores $l_{ij}$ y de $u_{ij}$ serán los resultados del proceso.*

* **Paso 2: Obtención de la Matriz U (Upper Triangular o Trangular Superior)**

El objetivo principal es transformar la matriz $A$ en una matriz triangular superior $U$ utilizando operaciones elementales de fila ( o sea la eliminación Gaussiana). Estas operaciones se aplican para hacer ceros por debajo de la diagonal principal.

Tenemos nuestra matriz $A$ de $3x3$:

$$A = \begin{bmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{bmatrix}$$

- Paso 2.1: Para obtener nuestra matriz $U$ debemos hacer ceros en la primera columna debajo de $a_{11}$

Para hacer $a_{21}$ cero, aplicamos la operación de fila $F_2 \leftarrow F_2 - (\frac{a_{21}}{a_{11}})F_1$.
El multiplicador es $l_{21} = \frac{a_{21}}{a_{11}}$. Anotamos el resultado de dicha división en la posición $l_{21}$ de la matriz $L$

Para hacer $a_{31}$ cero, aplicamos la operación de fila $F_3 \leftarrow F_3 - (\frac{a_{31}}{a_{11}})F_1$.
El multiplicador es $l_{31} = \frac{a_{31}}{a_{11}}$. También anotamos el resultado de dicha división en la posición $l_{31}$ de la matriz $L$

Después de estas operaciones, la matriz se verá así:

$$\begin{bmatrix} a_{11} & a_{12} & a_{13} \\ 0 & a'_{22} & a'_{23} \\ 0 & a'_{32} & a'_{33} \end{bmatrix} $$

Mientras que la Matriz $L$ tendrá anotados ya los elementos de la primera columna bajo $a_{11}$, es decir $l_{21}$ $l_{31}$

* Paso 2.2: Hacer ceros en la segunda columna debajo de $a'_{22}$

Ahora, para hacer $a'_{32}$ cero, aplicamos la operación de fila $F_3 \leftarrow F_3 - (\frac{a'_{32}}{a'_{22}})F_2$.
El multiplicador es $l_{32} = \frac{a'_{32}}{a'_{22}}$. Y anotamos por último el resultado de la división (el multiplicador) en la posición $l_{32}$ de la matriz $L$.

Finalmente, obtenemos la matriz $U$:

$$U = \begin{bmatrix} u_{11} & u_{12} & u_{13} \\ 0 & u_{22} & u_{23} \\ 0 & 0 & u_{33} \end{bmatrix}$$

Donde $u_{ij}$ son los elementos de la matriz resultante después de la eliminación Gaussiana.


* **Paso 3: Obtención y revisión de la Matriz L (Lower Triangular)**

La matriz $L$ (lower triangular) se construye con los multiplicadores que utilizamos en el proceso de eliminación Gaussiana para obtener $U$.

$$L = \begin{bmatrix} 1 & 0 & 0 \\ l_{21} & 1 & 0 \\ l_{31} & l_{32} & 1 \end{bmatrix}$$

Donde:
* $l_{21} = \frac{a_{21}}{a_{11}}$ (el multiplicador para hacer cero $a_{21}$)
* $l_{31} = \frac{a_{31}}{a_{11}}$ (el multiplicador para hacer cero $a_{31}$)
* $l_{32} = \frac{a'_{32}}{a'_{22}}$ (el multiplicador para hacer cero $a'_{32}$)

**Etiqueta:** *Multiplicadores de Eliminación Gaussiana*

Con $L$ y $U$ obtenidas, hemos concluido la factorización de la matriz $A$ en el producto de una matriz triangular inferior $L$ y una matriz triangular superior $U$, es decir, $A = LU$.

##**1.1 Guión y videotutorial de factorización LU**

##**1.2 Resolucion de Sistema de Ecuaciones**

El proceso de resolución mediante la factorización $LU$ consiste en transformar el problema original $Ax = b$ en dos sistemas triangulares más sencillos. Dado que $A = LU$, el sistema se reescribe como $L(Ux) = b$.

Metodología de resolución:

Sustitución hacia adelante: Se define un vector auxiliar $y$ tal que $Ly = b$. Al ser $L$ una matriz triangular inferior, las incógnitas se despejan de arriba hacia abajo.

Sustitución hacia atrás: Una vez hallado $y$, se resuelve el sistema $Ux = y$. Al ser $U$ una matriz triangular superior, las incógnitas finales de $x$ se despejan de abajo hacia arriba.Ejemplo General de AplicaciónPara ilustrar este proceso, consideremos la matriz $A = \begin{pmatrix} 2 & 1 \\ 6 & 8 \end{pmatrix}$ y el vector de términos independientes $b = \begin{pmatrix} 5 \\ 25 \end{pmatrix}$.

1. Obtención de L y U:
Mediante la eliminación de Gauss, factorizamos $A$:
$$L = \begin{pmatrix} 1 & 0 \\ 3 & 1 \end{pmatrix}, \quad U = \begin{pmatrix} 2 & 1 \\ 0 & 5 \end{pmatrix}$$

2. Resolución de $Ly = b$ (Sustitución hacia adelante):$$\begin{pmatrix} 1 & 0 \\ 3 & 1 \end{pmatrix} \begin{pmatrix} y_1 \\ y_2 \end{pmatrix} = \begin{pmatrix} 5 \\ 25 \end{pmatrix}$$$y_1 = 5$ $3(y_1) + y_2 = 25 \implies 3(5) + y_2 = 25 \implies y_2 = 10$

3. Resolución de $Ux = y$ (Sustitución hacia atrás):$$\begin{pmatrix} 2 & 1 \\ 0 & 5 \end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \end{pmatrix} = \begin{pmatrix} 5 \\ 10 \end{pmatrix}$$$5x_2 = 10 \implies x_2 = 2$ $2x_1 + x_2 = 5 \implies 2x_1 + 2 = 5 \implies 2x_1 = 3 \implies x_1 = 1.5$

Interpretación: La solución del sistema es $x = \begin{pmatrix} 1.5 \\ 2 \end{pmatrix}$. Este ejemplo demuestra cómo la descomposición facilita el cálculo al evitar operaciones complejas de inversión de matrices.

# **2. Aplicación práctica de la Factorizacion LU**

###* **Aplicacion en Ingeniería Estructural (Equilibrio de Fuerzas)**

En ingeniería estructural la factorización LU es fundamental cuando se analizan estructuras estáticamente determinadas o indeterminadas (como cerchas, marcos o vigas) mediante el Método de la Rigidez.


1. Problema: Una Cercha de dos barras
Imagina un nodo superior donde se unen dos barras de acero que están ancladas al suelo. Aplicamos una carga externa $P$ (una fuerza con componentes en $x$ e $y$) y queremos encontrar los desplazamientos del nodo ($d_1, d_2$).

El equilibrio de la estructura se define por la ecuación fundamental:

$$K \cdot \mathbf{d} = \mathbf{F}$$
Donde:

$K$: Matriz de rigidez global (propiedades del material y geometría).

$d$: Vector de desplazamientos desconocidos.

$F$: Vector de cargas externas aplicadas.

Ahora bien, supongamos que tenemos una viga simple discretizada en dos segmentos, donde queremos calcular los desplazamientos en dos puntos intermedios (nodos). La relación entre las fuerzas aplicadas y los desplazamientos se modela a través de una matriz de rigidez $K$.

Las ecuaciones de equilibrio resultantes son:

$$2d_1 - d_2 = 10$$
$$-d_1 + 3d_2 = 5$$

1. Representación Matricial ($Kd = F$)

La matriz de rigidez $K$ y el vector de fuerzas $F$ son:
$$K = \begin{pmatrix} 2 & -1 \\ -1 & 3 \end{pmatrix}, \quad F = \begin{pmatrix} 10 \\ 5 \end{pmatrix}$$

2. Factorización LU (Comandos de Python)

Aplicando la factorización LU, obtendríamos las siguientes matrices (estos valores son el resultado del proceso de eliminación aplicado en la matriz $K$):

Matriz L (Lower):
$$L = \begin{pmatrix} 1 & 0 \\ -0.5 & 1 \end{pmatrix}$$
Matriz U (Upper):
$$U = \begin{pmatrix} 2 & -1 \\ 0 & 2.5 \end{pmatrix}$$

3. Sustitución y Resultados

Primero resolvemos $Ly = F$ para encontrar un vector intermedio $y$, y luego $Ud = y$ para hallar los desplazamientos finales $d$.

Anticipamos un resultado similar a:

$d_1$ (Desplazamiento en el Nodo 1): $7.0$

$d_2$ (Desplazamiento en el Nodo 2): $4.0$



------------
###* **Aplicacion en Economía (Modelo de insumo-producto o similar)**

La factorización $LU$ es una herramienta fundamental en el álgebra lineal computacional, y su aplicación en economía es especialmente potente cuando trabajamos con el **Modelo de Insumo-Producto de Leontief**.

Este modelo busca determinar los niveles de producción necesarios para satisfacer tanto la demanda intermedia (entre industrias) como la demanda externa (consumidores).

1. EL PROBLEMA: Equilibrio de Producción en una Red

   Imagina un nodo central donde se cruzan dos industrias:
   Siderurgia (Acero) y Minería (Carbón).
   Para que el nodo esté en equilibrio, la producción total
   debe satisfacer tanto el consumo interno (lo que las
   industrias se piden entre sí) como la demanda externa
   (lo que el mercado solicita).


El equilibrio se define por la ecuación fundamental:



$$A \cdot \mathbf{x} = \mathbf{d}$$
                    

Donde:
* $A$ (Matriz de Leontief): Es la "Matriz de Rigidez Económica".
  
* $x$ (Vector de Producción): Son los "Desplazamientos
  Económicos" desconocidos (cuánto deben producir las fábricas).
* $d$ (Vector de Demanda Final): Son las "Cargas Externas".
  


---------------
###* **Aplicacion en Ciencias Ambientales (Movimiento o dispersión de contaminantes)**

En Ciencias Ambientales la factorización LU permite respuestas inmediatas, ya que funciona como una herramienta que simula modelos lo que seria los sistemas de ecuaciones por lo que al aplicar este metodo si existe un cambio en terminos independientes solo se harían sustituciones en vez de desarrollarse desde 0 toda la resolucion.

* Aplicación: Un cientifico de Datos trabaja en una organización de
ambiental y monitorea la salud del ecosistema hibrido en las Islas Galápagos, allí el sistema cuenta con 3 lagos interconectados. Y en estos se detecta un fertilizante no identificado y se necesita calcular la concentracion de cada lago para activar una alerta del contaminante invasor.
Ahora el flujo de estos lagos crean un equilibrio dinamico por lo que se puede modelar a un sistema de ecuaciones, las incognitas $x1,x2,x3$ representan las concentraciones.

Lago A (Entrada principal) $2x_1-x_2-x_3=9$

Lago B (Interconexión) $4x_1 + 3x_2 + 3x_3 = 23$

Lago C (Salida al mar) $2x_1 + x_2 + 2x_3 = 10$

1. Representación Matricial ($Ax = b$)

Donde:

 $A$: Representa la estructura física de conexión entre los lagos.

 $b$: Representa los datos medidos por los sensores.

 $x$: Representa las concentraciones del contaminante

$$A = \begin{pmatrix} 2 & 1 & 1 \\ 4 & 3 & 3 \\ 2 & 1 & 2 \end{pmatrix}, \quad b = \begin{pmatrix} 9 \\ 23 \\ 10 \end{pmatrix}$$

2. Factorización LU (Comandos de Python)

Matriz L (Lower): Contiene los multiplicadores del flujo.$$L = \begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 0 \\ 1 & 0 & 1 \end{pmatrix}$$Matriz U (Upper): Contiene el sistema simplificado tras la eliminación.
$$U = \begin{pmatrix} 2 & 1 & 1 \\ 0 & 1 & 1 \\ 0 & 0 & 1 \end{pmatrix}$$

3. Sustitución y Resultados

Primero resolvemos $Ly = b$ para encontrar un estado intermedio del sistema, y luego $Ux = y$ para hallar las concentraciones finales.
Resultado de la ejecución:

$x_1$ (Lago A): $2.0$ mg/L

$x_2$ (Lago B): $4.0$ mg/L

$x_3$ (Lago C): $1.0$ mg/L

##2.1 Resolución de ejercicios de aplicación


### Ejercicio de aplicación en Ingeniería

In [ ]:
import numpy as np

def factorizacion_lu_paso_a_paso(A_in, b_in):
    A = A_in.copy().astype(float)
    b = b_in.copy().astype(float)
    n = len(A)
    L = np.eye(n) # Matriz Identidad inicial

    print("=== PROCESO DE FACTORIZACIÓN LU (INGENIERÍA ESTRUCTURAL) ===\n")
    print("Matriz inicial K:")
    print(A)
    print("-" * 30)

    # Eliminación Gaussiana para encontrar L y U
    for i in range(n):
        # Evitar división por cero si el pivote es 0
        if A[i, i] == 0:
            raise ValueError("Pivot element is zero, LU factorization may not be possible without pivoting.")

        for j in range(i + 1, n):
            # Calcular el factor (multiplicador)
            factor = A[j, i] / A[i, i]
            L[j, i] = factor

            print(f"Operación: Fila {j+1} = Fila {j+1} - ({factor:.3f}) * Fila {i+1}")

            # Aplicar la operación a la fila de la matriz A
            A[j, i:] = A[j, i:] - factor * A[i, i:]

            print(A)
            print("-" * 30)

    U = A
    print("\n[RESULTADO DE LA DESCOMPOSICIÓN]")
    print(f"Matriz L (Lower, multiplicadores):\n{L}")
    print(f"\nMatriz U (Upper, triangular superior):\n{U}")
    print("=" * 60)

    # Resolución del sistema: Ly = F (Sustitución hacia adelante)
    y = np.zeros(n)
    for i in range(n):
        sum_ly = np.dot(L[i, :i], y[:i])
        y[i] = b[i] - sum_ly

    print(f"\n1. Resolviendo Ly = F para el vector intermedio y:")
    print(f"Vector y: {y}")

    # Resolución del sistema: Ud = y (Sustitución hacia atrás)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        sum_ux = np.dot(U[i, i+1:], x[i+1:])
        x[i] = (y[i] - sum_ux) / U[i, i]

    print(f"\n2. Resolviendo Ud = y para el vector de desplazamientos d:")
    print(f"Vector de desplazamientos d: {x}")
    print("\n" + "=" * 60)

# --- Datos del problema de Ingeniería Estructural ---
# Matriz de rigidez K
K_struct = np.array([
    [2, -1],
    [-1, 3]
])

# Vector de fuerzas F
F_struct = np.array([10, 5])

# Ejecutar la función
factorizacion_lu_paso_a_paso(K_struct, F_struct)

=== PROCESO DE FACTORIZACIÓN LU (INGENIERÍA ESTRUCTURAL) ===

Matriz inicial K:
[[ 2. -1.]
 [-1.  3.]]
------------------------------
Operación: Fila 2 = Fila 2 - (-0.500) * Fila 1
[[ 2.  -1. ]
 [ 0.   2.5]]
------------------------------

[RESULTADO DE LA DESCOMPOSICIÓN]
Matriz L (Lower, multiplicadores):
[[ 1.   0. ]
 [-0.5  1. ]]

Matriz U (Upper, triangular superior):
[[ 2.  -1. ]
 [ 0.   2.5]]

1. Resolviendo Ly = F para el vector intermedio y:
Vector y: [10. 10.]

2. Resolviendo Ud = y para el vector de desplazamientos d:
Vector de desplazamientos d: [7. 4.]



### Ejercicio de aplicación en Economía

In [ ]:
import numpy as np

# Definimos la matriz A y el vector d
A = np.array([[0.8, -0.2, -0.1],
              [-0.3, 0.7, -0.3],
              [-0.1, -0.3, 0.6]])
d = np.array([50, 40, 30])

# Creamos la matriz aumentada
AB = np.column_stack((A, d.astype(float)))

print("--- MATRIZ INICIAL ---")
print(AB)

# PASO 1: Limpiar la primera columna (debajo del 0.8)
# Eliminar el -0.3 de la fila 2
m21 = AB[1,0] / AB[0,0] # -0.3 / 0.8 = -0.375
AB[1] = AB[1] - m21 * AB[0]

# Eliminar el -0.1 de la fila 3
m31 = AB[2,0] / AB[0,0] # -0.1 / 0.8 = -0.125
AB[2] = AB[2] - m31 * AB[0]

print(f"\n--- TRAS LIMPIAR COLUMNA 1 (Factores: {m21}, {m31}) ---")
print(AB.round(3))

# PASO 2: Limpiar la segunda columna (debajo del nuevo pivote en F2,C2)
# El nuevo valor en AB[1,1] es el pivote. Vamos a eliminar el valor de abajo.
m32 = AB[2,1] / AB[1,1]
AB[2] = AB[2] - m32 * AB[1]

print(f"\n--- TRAS LIMPIAR COLUMNA 2 (Matriz Triangular Superior) ---")
print(AB.round(3))

# PASO 3: Sustitución hacia atrás
x = np.zeros(3)
x[2] = AB[2,3] / AB[2,2]
x[1] = (AB[1,3] - AB[1,2]*x[2]) / AB[1,1]
x[0] = (AB[0,3] - AB[0,2]*x[2] - AB[0,1]*x[1]) / AB[0,0]

print("\n--- RESULTADO FINAL (Producción x) ---")
print(f"Agricultura: {x[0]:.2f}")
print(f"Manufactura: {x[1]:.2f}")
print(f"Energía:     {x[2]:.2f}")

--- MATRIZ INICIAL ---
[[ 0.8 -0.2 -0.1 50. ]
 [-0.3  0.7 -0.3 40. ]
 [-0.1 -0.3  0.6 30. ]]

--- TRAS LIMPIAR COLUMNA 1 (Factores: -0.37499999999999994, -0.125) ---
[[ 0.8   -0.2   -0.1   50.   ]
 [ 0.     0.625 -0.337 58.75 ]
 [ 0.    -0.325  0.588 36.25 ]]

--- TRAS LIMPIAR COLUMNA 2 (Matriz Triangular Superior) ---
[[ 0.8   -0.2   -0.1   50.   ]
 [ 0.     0.625 -0.337 58.75 ]
 [ 0.     0.     0.412 66.8  ]]

--- RESULTADO FINAL (Producción x) ---
Agricultura: 128.16
Manufactura: 181.55
Energía:     162.14


### Ejercicio de aplicación en Ciencias Ambientales

In [ ]:
import numpy as np

def factorizacion_lu_paso_a_paso(A_in, b_in):
    A = A_in.copy().astype(float)
    b = b_in.copy().astype(float)
    n = len(A)
    L = np.eye(n) # Matriz Identidad inicial

    print("=== PROCESO DE FACTORIZACIÓN LU ===\n")
    print("Matriz inicial A:")
    print(A)
    print("-" * 30)

    # Eliminación Gaussiana para encontrar L y U
    for i in range(n):
        for j in range(i + 1, n):
            # Calcular el factor (multiplicador)
            factor = A[j, i] / A[i, i]
            L[j, i] = factor

            print(f"Operación: Fila {j+1} = Fila {j+1} - ({factor:.2f}) * Fila {i+1}")

            # Aplicar la operación a la fila de la matriz A
            A[j, i:] = A[j, i:] - factor * A[i, i:]

            print(A)
            print("-" * 30)

    U = A
    print("\n[RESULTADO DE LA DESCOMPOSICIÓN]")
    print(f"Matriz L (Multiplicadores):\n{L}")
    print(f"\nMatriz U (Triangular Superior):\n{U}")
    print("=" * 35)

    # Resolución del sistema: Ly = b (Sustitución hacia adelante)
    y = np.zeros(n)
    for i in range(n):
        sum_ly = np.dot(L[i, :i], y[:i])
        y[i] = b[i] - sum_ly

    print(f"\n1. Resolviendo Ly = b para y:")
    print(f"Vector intermedio y: {y}")

    # Resolución del sistema: Ux = y (Sustitución hacia atrás)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        sum_ux = np.dot(U[i, i+1:], x[i+1:])
        x[i] = (y[i] - sum_ux) / U[i, i]

    print(f"\n2. Resolviendo Ux = y para x:")
    print(f"Vector solución final x: {x}")
    print("\n" + "=" * 35)

# --- Datos del problema ---
A_lacos = np.array([
    [2, 1, 1],
    [4, 3, 3],
    [2, 1, 2]
])
b_lagos = np.array([9, 23, 10])

# Ejecutar la función
factorizacion_lu_paso_a_paso(A_lacos, b_lagos)

=== PROCESO DE FACTORIZACIÓN LU ===

Matriz inicial A:
[[2. 1. 1.]
 [4. 3. 3.]
 [2. 1. 2.]]
------------------------------
Operación: Fila 2 = Fila 2 - (2.00) * Fila 1
[[2. 1. 1.]
 [0. 1. 1.]
 [2. 1. 2.]]
------------------------------
Operación: Fila 3 = Fila 3 - (1.00) * Fila 1
[[2. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
------------------------------
Operación: Fila 3 = Fila 3 - (0.00) * Fila 2
[[2. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
------------------------------

[RESULTADO DE LA DESCOMPOSICIÓN]
Matriz L (Multiplicadores):
[[1. 0. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]

Matriz U (Triangular Superior):
[[2. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]

1. Resolviendo Ly = b para y:
Vector intermedio y: [9. 5. 1.]

2. Resolviendo Ux = y para x:
Vector solución final x: [2. 4. 1.]



# 3. Conclusión


# 4. Referencias

Larson, R. (2015). Fundamentos de álgebra lineal (7.ª ed.). Cengage Learning.

Kuttler, K. (2022, 30 de octubre). 2.10: Factorización LU. LibreTexts Español. https://espanol.libretexts.org/Bookshelves/Matematicas/Algebra_lineal/Un_Primer_Curso_de_%C3%81lgebra_Lineal_(Kuttler)/02%3A_Matrices/2.10%3A_Factorizaci%C3%B3n_LU
